import { NextResponse } from 'next/server';
import { Decimal } from 'decimal.js';
import prisma from '@/lib/db/prisma';
import { reconcileLedgerBalances } from '@/lib/db/ledger';
import { getAuthenticatedAccount } from '@/lib/auth/session';
import { calculateTradeFinancials } from '@/lib/engine/financial-engine';
import { startOfTradingDate } from '@/lib/engine/trading-date';
import { createTradeSchema } from '@/lib/validators/schemas';
import type { TradingSettingsInput, TradeCalculationInput } from '@/types';
export const dynamic = 'force-dynamic';

const json=(data:unknown,status=200)=>NextResponse.json({success:status<400,data}, {status});
function dayKey(date:Date,timezone:string){return new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(date)}
export async function GET(){try{const {error,account}=await getAuthenticatedAccount();if(error)return error;const rows=await prisma.trade.findMany({where:{accountId:account!.id},orderBy:{timestamp:'desc'}});return json(rows)}catch{return json({error:'Unable to load trades.'},500)}}
export async function POST(request:Request){try{const {error,account}=await getAuthenticatedAccount();if(error)return error;const parsed=createTradeSchema.safeParse(await request.json());if(!parsed.success)return json({error:'Invalid trade details.',details:parsed.error.flatten()},400);const data=parsed.data;const setting=account!.tradingSettings!;const calc=calculateTradeFinancials({direction:data.direction,entryPriceUsd:new Decimal(data.entryPriceUsd),exitPriceUsd:new Decimal(data.exitPriceUsd),lots:data.lots,leverage:data.leverage,entryOrderType:data.entryOrderType,exitOrderType:data.exitOrderType,fundingType:data.fundingType,fundingAmountUsd:new Decimal(data.fundingAmountUsd||0)} as TradeCalculationInput,{fxRateUsdToInr:new Decimal(setting.fxRateUsdToInr),makerFeeRate:new Decimal(setting.makerFeeRate),takerFeeRate:new Decimal(setting.takerFeeRate),gstRate:new Decimal(setting.gstRate),lotsPerEth:setting.lotsPerEth,defaultLeverage:setting.defaultLeverage,dailyTargetRate:new Decimal(setting.dailyTargetRate),timezone:setting.timezone} as TradingSettingsInput);const timestamp=data.timestamp?new Date(data.timestamp):new Date();const tradingDate=new Date(`${dayKey(timestamp,setting.timezone)}T00:00:00.000Z`);const saved=await prisma.$transaction(async tx=>{const trade=await tx.trade.create({data:{accountId:account!.id,timestamp,tradingDate,direction:data.direction,entryPriceUsd:calc.ethQuantity.isFinite()?data.entryPriceUsd:0,exitPriceUsd:data.exitPriceUsd,lots:data.lots,ethQuantity:calc.ethQuantity.toFixed(8),leverage:data.leverage,entryOrderType:data.entryOrderType,exitOrderType:data.exitOrderType,entryNotionalUsd:calc.entryNotionalUsd.toFixed(4),exitNotionalUsd:calc.exitNotionalUsd.toFixed(4),grossPnlUsd:calc.grossPnlUsd.toFixed(4),entryFeeUsd:calc.entryFeeUsd.toFixed(6),exitFeeUsd:calc.exitFeeUsd.toFixed(6),totalFeesUsd:calc.totalFeesUsd.toFixed(6),gstUsd:calc.gstUsd.toFixed(6),fundingType:data.fundingType,fundingAmountUsd:new Decimal(data.fundingAmountUsd||0).toFixed(6),fundingNetUsd:calc.fundingNetUsd.toFixed(6),netPnlUsd:calc.netPnlUsd.toFixed(4),fxRateUsed:calc.fxRateUsed.toFixed(4),netPnlInr:calc.netPnlInr.toFixed(4),estimatedMarginInr:calc.estimatedMarginInr.toFixed(4),setup:data.setup,emotion:data.emotion,mistake:data.mistake,notes:data.notes}});
 await tx.feeRecord.createMany({data:[{tradeId:trade.id,feeType:'ENTRY',orderType:data.entryOrderType,rate:(data.entryOrderType==='MAKER'?setting.makerFeeRate:setting.takerFeeRate),notionalUsd:calc.entryNotionalUsd.toFixed(4),feeAmountUsd:calc.entryFeeUsd.toFixed(6)},{tradeId:trade.id,feeType:'EXIT',orderType:data.exitOrderType,rate:(data.exitOrderType==='MAKER'?setting.makerFeeRate:setting.takerFeeRate),notionalUsd:calc.exitNotionalUsd.toFixed(4),feeAmountUsd:calc.exitFeeUsd.toFixed(6)}]});
 const previousEntries=await tx.ledgerEntry.findMany({where:{accountId:account!.id}});const balanceBefore=previousEntries.reduce((sum,e)=>sum.add(e.amountInr.toString()),new Decimal(0));
 await tx.ledgerEntry.create({data:{accountId:account!.id,tradeId:trade.id,type:calc.netPnlInr.gte(0)?'TRADE_PROFIT':'TRADE_LOSS',amountInr:calc.netPnlInr.toFixed(4),balanceAfter:balanceBefore.add(calc.netPnlInr).toFixed(8),description:`${data.direction} ETHUSD trade` ,timestamp}});
 const dayTrades=await tx.trade.findMany({where:{accountId:account!.id,tradingDate},orderBy:{timestamp:'asc'}});const allBefore=await tx.ledgerEntry.findMany({where:{accountId:account!.id,timestamp:{lt:startOfTradingDate(dayKey(timestamp,setting.timezone),setting.timezone)}},orderBy:{timestamp:'asc'}});let bod=new Decimal(0);for(const e of allBefore)bod=bod.add(e.amountInr.toString());const dayPnl=dayTrades.reduce((a,t)=>a.add(t.netPnlInr.toString()),new Decimal(0));const target=new Decimal(bod).mul(setting.dailyTargetRate);const ending=bod.add(dayPnl);await tx.tradingDay.upsert({where:{accountId_date:{accountId:account!.id,date:tradingDate}},create:{accountId:account!.id,date:tradingDate,beginningCapital:bod.toFixed(4),targetRate:setting.dailyTargetRate,targetProfit:target.toFixed(4),targetCapital:bod.add(target).toFixed(4),targetDifference:dayPnl.sub(target).toFixed(4),targetAchieved:dayPnl.gte(target),actualPnl:dayPnl.toFixed(4),endingCapital:ending.toFixed(4),tradeCount:dayTrades.length,targetStatus:dayPnl.gte(target)?'ACHIEVED':'IN_PROGRESS'},update:{beginningCapital:bod.toFixed(4),targetRate:setting.dailyTargetRate,targetProfit:target.toFixed(4),targetCapital:bod.add(target).toFixed(4),targetDifference:dayPnl.sub(target).toFixed(4),targetAchieved:dayPnl.gte(target),actualPnl:dayPnl.toFixed(4),endingCapital:ending.toFixed(4),tradeCount:dayTrades.length,targetStatus:dayPnl.gte(target)?'ACHIEVED':'IN_PROGRESS'}});return trade});return json(saved,201)}catch(e){console.error('Trade create failed',e);return json({error:'Unable to record trade.'},500)}}
